// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization_decisions.sql

package auditdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuthorizationDecision = `-- name: GetAuthorizationDecision :one
SELECT decision_id, environment_id, request_id, attempt_id, attempt_number, decision_payload_sha256, correlation_id, correlation_source, causation_id, decision_stage, route_id, route_contract_version, http_method, route_template, principal_type, subject_id, actor_id, delegator_id, credential_id_sha256, oidc_issuer, oidc_audience, active_organization_id, action, resource_type, resource_id, openfga_store_id, openfga_model_id, openfga_model_sha256, openfga_user, openfga_relation, openfga_object, contextual_tuples_sha256, contextual_tuples_canonical_version, result, reason_code, openfga_latency_ms, openfga_attempts, actor_context_jti, actor_context_kid, actor_context_audience, actor_context_sha256, actor_context_issued_at, actor_context_expires_at, decided_at
FROM authorizer_audit.authorization_decisions
WHERE environment_id = $1
  AND decision_id = $2
`

type GetAuthorizationDecisionParams struct {
	EnvironmentID string      `db:"environment_id" json:"environment_id"`
	DecisionID    pgtype.UUID `db:"decision_id" json:"decision_id"`
}

func (q *Queries) GetAuthorizationDecision(ctx context.Context, arg GetAuthorizationDecisionParams) (*AuthorizerAuditAuthorizationDecision, error) {
	row := q.db.QueryRow(ctx, getAuthorizationDecision, arg.EnvironmentID, arg.DecisionID)
	var i AuthorizerAuditAuthorizationDecision
	err := row.Scan(
		&i.DecisionID,
		&i.EnvironmentID,
		&i.RequestID,
		&i.AttemptID,
		&i.AttemptNumber,
		&i.DecisionPayloadSha256,
		&i.CorrelationID,
		&i.CorrelationSource,
		&i.CausationID,
		&i.DecisionStage,
		&i.RouteID,
		&i.RouteContractVersion,
		&i.HttpMethod,
		&i.RouteTemplate,
		&i.PrincipalType,
		&i.SubjectID,
		&i.ActorID,
		&i.DelegatorID,
		&i.CredentialIDSha256,
		&i.OidcIssuer,
		&i.OidcAudience,
		&i.ActiveOrganizationID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.OpenfgaStoreID,
		&i.OpenfgaModelID,
		&i.OpenfgaModelSha256,
		&i.OpenfgaUser,
		&i.OpenfgaRelation,
		&i.OpenfgaObject,
		&i.ContextualTuplesSha256,
		&i.ContextualTuplesCanonicalVersion,
		&i.Result,
		&i.ReasonCode,
		&i.OpenfgaLatencyMs,
		&i.OpenfgaAttempts,
		&i.ActorContextJti,
		&i.ActorContextKid,
		&i.ActorContextAudience,
		&i.ActorContextSha256,
		&i.ActorContextIssuedAt,
		&i.ActorContextExpiresAt,
		&i.DecidedAt,
	)
	return &i, err
}

const listAuthorizationDecisionsByCorrelation = `-- name: ListAuthorizationDecisionsByCorrelation :many
SELECT decision_id, environment_id, request_id, attempt_id, attempt_number, decision_payload_sha256, correlation_id, correlation_source, causation_id, decision_stage, route_id, route_contract_version, http_method, route_template, principal_type, subject_id, actor_id, delegator_id, credential_id_sha256, oidc_issuer, oidc_audience, active_organization_id, action, resource_type, resource_id, openfga_store_id, openfga_model_id, openfga_model_sha256, openfga_user, openfga_relation, openfga_object, contextual_tuples_sha256, contextual_tuples_canonical_version, result, reason_code, openfga_latency_ms, openfga_attempts, actor_context_jti, actor_context_kid, actor_context_audience, actor_context_sha256, actor_context_issued_at, actor_context_expires_at, decided_at
FROM authorizer_audit.authorization_decisions
WHERE environment_id = $1
  AND correlation_id = $2
ORDER BY decided_at, decision_id
`

type ListAuthorizationDecisionsByCorrelationParams struct {
	EnvironmentID string      `db:"environment_id" json:"environment_id"`
	CorrelationID pgtype.UUID `db:"correlation_id" json:"correlation_id"`
}

func (q *Queries) ListAuthorizationDecisionsByCorrelation(ctx context.Context, arg ListAuthorizationDecisionsByCorrelationParams) ([]*AuthorizerAuditAuthorizationDecision, error) {
	rows, err := q.db.Query(ctx, listAuthorizationDecisionsByCorrelation, arg.EnvironmentID, arg.CorrelationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AuthorizerAuditAuthorizationDecision{}
	for rows.Next() {
		var i AuthorizerAuditAuthorizationDecision
		if err := rows.Scan(
			&i.DecisionID,
			&i.EnvironmentID,
			&i.RequestID,
			&i.AttemptID,
			&i.AttemptNumber,
			&i.DecisionPayloadSha256,
			&i.CorrelationID,
			&i.CorrelationSource,
			&i.CausationID,
			&i.DecisionStage,
			&i.RouteID,
			&i.RouteContractVersion,
			&i.HttpMethod,
			&i.RouteTemplate,
			&i.PrincipalType,
			&i.SubjectID,
			&i.ActorID,
			&i.DelegatorID,
			&i.CredentialIDSha256,
			&i.OidcIssuer,
			&i.OidcAudience,
			&i.ActiveOrganizationID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.OpenfgaStoreID,
			&i.OpenfgaModelID,
			&i.OpenfgaModelSha256,
			&i.OpenfgaUser,
			&i.OpenfgaRelation,
			&i.OpenfgaObject,
			&i.ContextualTuplesSha256,
			&i.ContextualTuplesCanonicalVersion,
			&i.Result,
			&i.ReasonCode,
			&i.OpenfgaLatencyMs,
			&i.OpenfgaAttempts,
			&i.ActorContextJti,
			&i.ActorContextKid,
			&i.ActorContextAudience,
			&i.ActorContextSha256,
			&i.ActorContextIssuedAt,
			&i.ActorContextExpiresAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAuthorizationDecision = `-- name: RecordAuthorizationDecision :one
WITH inserted AS (
    INSERT INTO authorizer_audit.authorization_decisions (
        decision_id, environment_id, request_id, attempt_id, attempt_number,
        decision_payload_sha256, correlation_id, correlation_source, causation_id,
        decision_stage, route_id, route_contract_version, http_method, route_template,
        principal_type, subject_id, actor_id, delegator_id, credential_id_sha256,
        oidc_issuer, oidc_audience, active_organization_id, action, resource_type,
        resource_id, openfga_store_id, openfga_model_id, openfga_model_sha256,
        openfga_user, openfga_relation, openfga_object, contextual_tuples_sha256,
        contextual_tuples_canonical_version, result, reason_code, openfga_latency_ms,
        openfga_attempts, actor_context_jti, actor_context_kid,
        actor_context_audience, actor_context_sha256, actor_context_issued_at,
        actor_context_expires_at, decided_at
    ) VALUES (
        $1, $2, $3,
        $4, $5, $6,
        $7, $8, $9,
        $10, $11, $12,
        $13, $14, $15,
        $16, $17, $18,
        $19, $20, $21,
        $22, $23, $24,
        $25, $26, $27,
        $28, $29,
        $30, $31,
        $32, $33,
        $34, $35, $36,
        $37, $38,
        $39, $40,
        $41, $42,
        $43, $44
    )
    ON CONFLICT DO NOTHING
    RETURNING decision_id, environment_id, request_id, attempt_id, attempt_number, decision_payload_sha256, correlation_id, correlation_source, causation_id, decision_stage, route_id, route_contract_version, http_method, route_template, principal_type, subject_id, actor_id, delegator_id, credential_id_sha256, oidc_issuer, oidc_audience, active_organization_id, action, resource_type, resource_id, openfga_store_id, openfga_model_id, openfga_model_sha256, openfga_user, openfga_relation, openfga_object, contextual_tuples_sha256, contextual_tuples_canonical_version, result, reason_code, openfga_latency_ms, openfga_attempts, actor_context_jti, actor_context_kid, actor_context_audience, actor_context_sha256, actor_context_issued_at, actor_context_expires_at, decided_at
)
SELECT decision_id, environment_id, request_id, attempt_id, attempt_number, decision_payload_sha256, correlation_id, correlation_source, causation_id, decision_stage, route_id, route_contract_version, http_method, route_template, principal_type, subject_id, actor_id, delegator_id, credential_id_sha256, oidc_issuer, oidc_audience, active_organization_id, action, resource_type, resource_id, openfga_store_id, openfga_model_id, openfga_model_sha256, openfga_user, openfga_relation, openfga_object, contextual_tuples_sha256, contextual_tuples_canonical_version, result, reason_code, openfga_latency_ms, openfga_attempts, actor_context_jti, actor_context_kid, actor_context_audience, actor_context_sha256, actor_context_issued_at, actor_context_expires_at, decided_at FROM inserted
UNION ALL
SELECT decision_id, environment_id, request_id, attempt_id, attempt_number, decision_payload_sha256, correlation_id, correlation_source, causation_id, decision_stage, route_id, route_contract_version, http_method, route_template, principal_type, subject_id, actor_id, delegator_id, credential_id_sha256, oidc_issuer, oidc_audience, active_organization_id, action, resource_type, resource_id, openfga_store_id, openfga_model_id, openfga_model_sha256, openfga_user, openfga_relation, openfga_object, contextual_tuples_sha256, contextual_tuples_canonical_version, result, reason_code, openfga_latency_ms, openfga_attempts, actor_context_jti, actor_context_kid, actor_context_audience, actor_context_sha256, actor_context_issued_at, actor_context_expires_at, decided_at
FROM authorizer_audit.authorization_decisions
WHERE environment_id = $2
  AND decision_id = $1
  AND decision_payload_sha256 = $6
LIMIT 1
`

type RecordAuthorizationDecisionParams struct {
	DecisionID                       pgtype.UUID        `db:"decision_id" json:"decision_id"`
	EnvironmentID                    string             `db:"environment_id" json:"environment_id"`
	RequestID                        pgtype.UUID        `db:"request_id" json:"request_id"`
	AttemptID                        pgtype.UUID        `db:"attempt_id" json:"attempt_id"`
	AttemptNumber                    int32              `db:"attempt_number" json:"attempt_number"`
	DecisionPayloadSha256            string             `db:"decision_payload_sha256" json:"decision_payload_sha256"`
	CorrelationID                    pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	CorrelationSource                string             `db:"correlation_source" json:"correlation_source"`
	CausationID                      pgtype.UUID        `db:"causation_id" json:"causation_id"`
	DecisionStage                    string             `db:"decision_stage" json:"decision_stage"`
	RouteID                          *string            `db:"route_id" json:"route_id"`
	RouteContractVersion             *string            `db:"route_contract_version" json:"route_contract_version"`
	HttpMethod                       *string            `db:"http_method" json:"http_method"`
	RouteTemplate                    *string            `db:"route_template" json:"route_template"`
	PrincipalType                    *string            `db:"principal_type" json:"principal_type"`
	SubjectID                        *string            `db:"subject_id" json:"subject_id"`
	ActorID                          *string            `db:"actor_id" json:"actor_id"`
	DelegatorID                      *string            `db:"delegator_id" json:"delegator_id"`
	CredentialIDSha256               *string            `db:"credential_id_sha256" json:"credential_id_sha256"`
	OidcIssuer                       *string            `db:"oidc_issuer" json:"oidc_issuer"`
	OidcAudience                     *string            `db:"oidc_audience" json:"oidc_audience"`
	ActiveOrganizationID             pgtype.UUID        `db:"active_organization_id" json:"active_organization_id"`
	Action                           *string            `db:"action" json:"action"`
	ResourceType                     *string            `db:"resource_type" json:"resource_type"`
	ResourceID                       *string            `db:"resource_id" json:"resource_id"`
	OpenfgaStoreID                   *string            `db:"openfga_store_id" json:"openfga_store_id"`
	OpenfgaModelID                   *string            `db:"openfga_model_id" json:"openfga_model_id"`
	OpenfgaModelSha256               *string            `db:"openfga_model_sha256" json:"openfga_model_sha256"`
	OpenfgaUser                      *string            `db:"openfga_user" json:"openfga_user"`
	OpenfgaRelation                  *string            `db:"openfga_relation" json:"openfga_relation"`
	OpenfgaObject                    *string            `db:"openfga_object" json:"openfga_object"`
	ContextualTuplesSha256           *string            `db:"contextual_tuples_sha256" json:"contextual_tuples_sha256"`
	ContextualTuplesCanonicalVersion *string            `db:"contextual_tuples_canonical_version" json:"contextual_tuples_canonical_version"`
	Result                           string             `db:"result" json:"result"`
	ReasonCode                       string             `db:"reason_code" json:"reason_code"`
	OpenfgaLatencyMs                 *int32             `db:"openfga_latency_ms" json:"openfga_latency_ms"`
	OpenfgaAttempts                  *int32             `db:"openfga_attempts" json:"openfga_attempts"`
	ActorContextJti                  pgtype.UUID        `db:"actor_context_jti" json:"actor_context_jti"`
	ActorContextKid                  *string            `db:"actor_context_kid" json:"actor_context_kid"`
	ActorContextAudience             *string            `db:"actor_context_audience" json:"actor_context_audience"`
	ActorContextSha256               *string            `db:"actor_context_sha256" json:"actor_context_sha256"`
	ActorContextIssuedAt             pgtype.Timestamptz `db:"actor_context_issued_at" json:"actor_context_issued_at"`
	ActorContextExpiresAt            pgtype.Timestamptz `db:"actor_context_expires_at" json:"actor_context_expires_at"`
	DecidedAt                        pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
}

type RecordAuthorizationDecisionRow struct {
	DecisionID                       pgtype.UUID        `db:"decision_id" json:"decision_id"`
	EnvironmentID                    string             `db:"environment_id" json:"environment_id"`
	RequestID                        pgtype.UUID        `db:"request_id" json:"request_id"`
	AttemptID                        pgtype.UUID        `db:"attempt_id" json:"attempt_id"`
	AttemptNumber                    int32              `db:"attempt_number" json:"attempt_number"`
	DecisionPayloadSha256            string             `db:"decision_payload_sha256" json:"decision_payload_sha256"`
	CorrelationID                    pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	CorrelationSource                string             `db:"correlation_source" json:"correlation_source"`
	CausationID                      pgtype.UUID        `db:"causation_id" json:"causation_id"`
	DecisionStage                    string             `db:"decision_stage" json:"decision_stage"`
	RouteID                          *string            `db:"route_id" json:"route_id"`
	RouteContractVersion             *string            `db:"route_contract_version" json:"route_contract_version"`
	HttpMethod                       *string            `db:"http_method" json:"http_method"`
	RouteTemplate                    *string            `db:"route_template" json:"route_template"`
	PrincipalType                    *string            `db:"principal_type" json:"principal_type"`
	SubjectID                        *string            `db:"subject_id" json:"subject_id"`
	ActorID                          *string            `db:"actor_id" json:"actor_id"`
	DelegatorID                      *string            `db:"delegator_id" json:"delegator_id"`
	CredentialIDSha256               *string            `db:"credential_id_sha256" json:"credential_id_sha256"`
	OidcIssuer                       *string            `db:"oidc_issuer" json:"oidc_issuer"`
	OidcAudience                     *string            `db:"oidc_audience" json:"oidc_audience"`
	ActiveOrganizationID             pgtype.UUID        `db:"active_organization_id" json:"active_organization_id"`
	Action                           *string            `db:"action" json:"action"`
	ResourceType                     *string            `db:"resource_type" json:"resource_type"`
	ResourceID                       *string            `db:"resource_id" json:"resource_id"`
	OpenfgaStoreID                   *string            `db:"openfga_store_id" json:"openfga_store_id"`
	OpenfgaModelID                   *string            `db:"openfga_model_id" json:"openfga_model_id"`
	OpenfgaModelSha256               *string            `db:"openfga_model_sha256" json:"openfga_model_sha256"`
	OpenfgaUser                      *string            `db:"openfga_user" json:"openfga_user"`
	OpenfgaRelation                  *string            `db:"openfga_relation" json:"openfga_relation"`
	OpenfgaObject                    *string            `db:"openfga_object" json:"openfga_object"`
	ContextualTuplesSha256           *string            `db:"contextual_tuples_sha256" json:"contextual_tuples_sha256"`
	ContextualTuplesCanonicalVersion *string            `db:"contextual_tuples_canonical_version" json:"contextual_tuples_canonical_version"`
	Result                           string             `db:"result" json:"result"`
	ReasonCode                       string             `db:"reason_code" json:"reason_code"`
	OpenfgaLatencyMs                 *int32             `db:"openfga_latency_ms" json:"openfga_latency_ms"`
	OpenfgaAttempts                  *int32             `db:"openfga_attempts" json:"openfga_attempts"`
	ActorContextJti                  pgtype.UUID        `db:"actor_context_jti" json:"actor_context_jti"`
	ActorContextKid                  *string            `db:"actor_context_kid" json:"actor_context_kid"`
	ActorContextAudience             *string            `db:"actor_context_audience" json:"actor_context_audience"`
	ActorContextSha256               *string            `db:"actor_context_sha256" json:"actor_context_sha256"`
	ActorContextIssuedAt             pgtype.Timestamptz `db:"actor_context_issued_at" json:"actor_context_issued_at"`
	ActorContextExpiresAt            pgtype.Timestamptz `db:"actor_context_expires_at" json:"actor_context_expires_at"`
	DecidedAt                        pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
}

func (q *Queries) RecordAuthorizationDecision(ctx context.Context, arg RecordAuthorizationDecisionParams) (*RecordAuthorizationDecisionRow, error) {
	row := q.db.QueryRow(ctx, recordAuthorizationDecision,
		arg.DecisionID,
		arg.EnvironmentID,
		arg.RequestID,
		arg.AttemptID,
		arg.AttemptNumber,
		arg.DecisionPayloadSha256,
		arg.CorrelationID,
		arg.CorrelationSource,
		arg.CausationID,
		arg.DecisionStage,
		arg.RouteID,
		arg.RouteContractVersion,
		arg.HttpMethod,
		arg.RouteTemplate,
		arg.PrincipalType,
		arg.SubjectID,
		arg.ActorID,
		arg.DelegatorID,
		arg.CredentialIDSha256,
		arg.OidcIssuer,
		arg.OidcAudience,
		arg.ActiveOrganizationID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.OpenfgaStoreID,
		arg.OpenfgaModelID,
		arg.OpenfgaModelSha256,
		arg.OpenfgaUser,
		arg.OpenfgaRelation,
		arg.OpenfgaObject,
		arg.ContextualTuplesSha256,
		arg.ContextualTuplesCanonicalVersion,
		arg.Result,
		arg.ReasonCode,
		arg.OpenfgaLatencyMs,
		arg.OpenfgaAttempts,
		arg.ActorContextJti,
		arg.ActorContextKid,
		arg.ActorContextAudience,
		arg.ActorContextSha256,
		arg.ActorContextIssuedAt,
		arg.ActorContextExpiresAt,
		arg.DecidedAt,
	)
	var i RecordAuthorizationDecisionRow
	err := row.Scan(
		&i.DecisionID,
		&i.EnvironmentID,
		&i.RequestID,
		&i.AttemptID,
		&i.AttemptNumber,
		&i.DecisionPayloadSha256,
		&i.CorrelationID,
		&i.CorrelationSource,
		&i.CausationID,
		&i.DecisionStage,
		&i.RouteID,
		&i.RouteContractVersion,
		&i.HttpMethod,
		&i.RouteTemplate,
		&i.PrincipalType,
		&i.SubjectID,
		&i.ActorID,
		&i.DelegatorID,
		&i.CredentialIDSha256,
		&i.OidcIssuer,
		&i.OidcAudience,
		&i.ActiveOrganizationID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.OpenfgaStoreID,
		&i.OpenfgaModelID,
		&i.OpenfgaModelSha256,
		&i.OpenfgaUser,
		&i.OpenfgaRelation,
		&i.OpenfgaObject,
		&i.ContextualTuplesSha256,
		&i.ContextualTuplesCanonicalVersion,
		&i.Result,
		&i.ReasonCode,
		&i.OpenfgaLatencyMs,
		&i.OpenfgaAttempts,
		&i.ActorContextJti,
		&i.ActorContextKid,
		&i.ActorContextAudience,
		&i.ActorContextSha256,
		&i.ActorContextIssuedAt,
		&i.ActorContextExpiresAt,
		&i.DecidedAt,
	)
	return &i, err
}
