// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auditdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthorizerAuditAuthorizationDecision struct {
	DecisionID                       pgtype.UUID        `db:"decision_id" json:"decision_id"`
	EnvironmentID                    string             `db:"environment_id" json:"environment_id"`
	RequestID                        pgtype.UUID        `db:"request_id" json:"request_id"`
	AttemptID                        pgtype.UUID        `db:"attempt_id" json:"attempt_id"`
	AttemptNumber                    int32              `db:"attempt_number" json:"attempt_number"`
	DecisionPayloadSha256            string             `db:"decision_payload_sha256" json:"decision_payload_sha256"`
	CorrelationID                    pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	CorrelationSource                string             `db:"correlation_source" json:"correlation_source"`
	CausationID                      pgtype.UUID        `db:"causation_id" json:"causation_id"`
	DecisionStage                    string             `db:"decision_stage" json:"decision_stage"`
	RouteID                          *string            `db:"route_id" json:"route_id"`
	RouteContractVersion             *string            `db:"route_contract_version" json:"route_contract_version"`
	HttpMethod                       *string            `db:"http_method" json:"http_method"`
	RouteTemplate                    *string            `db:"route_template" json:"route_template"`
	PrincipalType                    *string            `db:"principal_type" json:"principal_type"`
	SubjectID                        *string            `db:"subject_id" json:"subject_id"`
	ActorID                          *string            `db:"actor_id" json:"actor_id"`
	DelegatorID                      *string            `db:"delegator_id" json:"delegator_id"`
	CredentialIDSha256               *string            `db:"credential_id_sha256" json:"credential_id_sha256"`
	OidcIssuer                       *string            `db:"oidc_issuer" json:"oidc_issuer"`
	OidcAudience                     *string            `db:"oidc_audience" json:"oidc_audience"`
	ActiveOrganizationID             pgtype.UUID        `db:"active_organization_id" json:"active_organization_id"`
	Action                           *string            `db:"action" json:"action"`
	ResourceType                     *string            `db:"resource_type" json:"resource_type"`
	ResourceID                       *string            `db:"resource_id" json:"resource_id"`
	OpenfgaStoreID                   *string            `db:"openfga_store_id" json:"openfga_store_id"`
	OpenfgaModelID                   *string            `db:"openfga_model_id" json:"openfga_model_id"`
	OpenfgaModelSha256               *string            `db:"openfga_model_sha256" json:"openfga_model_sha256"`
	OpenfgaUser                      *string            `db:"openfga_user" json:"openfga_user"`
	OpenfgaRelation                  *string            `db:"openfga_relation" json:"openfga_relation"`
	OpenfgaObject                    *string            `db:"openfga_object" json:"openfga_object"`
	ContextualTuplesSha256           *string            `db:"contextual_tuples_sha256" json:"contextual_tuples_sha256"`
	ContextualTuplesCanonicalVersion *string            `db:"contextual_tuples_canonical_version" json:"contextual_tuples_canonical_version"`
	Result                           string             `db:"result" json:"result"`
	ReasonCode                       string             `db:"reason_code" json:"reason_code"`
	OpenfgaLatencyMs                 *int32             `db:"openfga_latency_ms" json:"openfga_latency_ms"`
	OpenfgaAttempts                  *int32             `db:"openfga_attempts" json:"openfga_attempts"`
	ActorContextJti                  pgtype.UUID        `db:"actor_context_jti" json:"actor_context_jti"`
	ActorContextKid                  *string            `db:"actor_context_kid" json:"actor_context_kid"`
	ActorContextAudience             *string            `db:"actor_context_audience" json:"actor_context_audience"`
	ActorContextSha256               *string            `db:"actor_context_sha256" json:"actor_context_sha256"`
	ActorContextIssuedAt             pgtype.Timestamptz `db:"actor_context_issued_at" json:"actor_context_issued_at"`
	ActorContextExpiresAt            pgtype.Timestamptz `db:"actor_context_expires_at" json:"actor_context_expires_at"`
	DecidedAt                        pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
}
