// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auditdb

import (
	"context"
)

type Querier interface {
	GetAuthorizationDecision(ctx context.Context, arg GetAuthorizationDecisionParams) (*AuthorizerAuditAuthorizationDecision, error)
	ListAuthorizationDecisionsByCorrelation(ctx context.Context, arg ListAuthorizationDecisionsByCorrelationParams) ([]*AuthorizerAuditAuthorizationDecision, error)
	RecordAuthorizationDecision(ctx context.Context, arg RecordAuthorizationDecisionParams) (*RecordAuthorizationDecisionRow, error)
}

var _ Querier = (*Queries)(nil)
